<%@page import="cl.femase.gestionweb.common.Constantes"%>
<%@page import="cl.femase.gestionweb.vo.UsuarioVO"%>
<%@page import="cl.femase.gestionweb.vo.EmpleadoVO"%>
<!--
Copyright 2017 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID: jqueryform-d81043
Date: 2017-11-30 14:39:30
Generated by http://www.jqueryform.com
-->
<%@page import="cl.femase.gestionweb.vo.CargoVO"%>
<%@page import="cl.femase.gestionweb.vo.ModuloAccesoPerfilVO"%>
<%@page import="cl.femase.gestionweb.vo.EmpresaVO"%>
<%@page import="cl.femase.gestionweb.vo.DepartamentoVO"%>
<%@page import="cl.femase.gestionweb.vo.CentroCostoVO"%>
<%@page import="cl.femase.gestionweb.vo.ComunaVO"%>
<%@page import="cl.femase.gestionweb.vo.TurnoVO"%>
<%@page import="java.util.LinkedHashMap"%>
<%@page import="java.util.List"%>
<%@page import="java.util.ArrayList"%>
<%@ page import="java.util.Collection"%>
<%@ page import="java.util.Iterator"%>
<!-- import para mostrar imagen-->
<%@page import="java.io.File"%>
<%@page import="java.io.IOException"%>
<%@page import="java.awt.image.BufferedImage"%>
<%@page import="javax.imageio.ImageIO"%>
<%@page import="java.io.ByteArrayOutputStream"%>
<%@page import="java.math.BigInteger"%>
<%@page import="javax.xml.bind.DatatypeConverter"%>
<%@page import="java.awt.image.BufferedImage"%>
<%@page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
    UsuarioVO theUser	= (UsuarioVO)session.getAttribute("usuarioObj");
    List<EmpresaVO> empresas = (List<EmpresaVO>)session.getAttribute("empresas");
    List<ComunaVO> comunas   = (List<ComunaVO>)session.getAttribute("comunas"); 
    EmpleadoVO empleado = (EmpleadoVO)session.getAttribute("empleado");
    List<CargoVO> cargos   = (List<CargoVO>)session.getAttribute("cargos");
    String imagesPath = (String)session.getAttribute("path_images"); 
    String strAccion = (String)request.getAttribute("action");
	System.out.println("[GestionFemaseWeb]form_modificar_empleado.jsp]strAccion: "+strAccion);
        
    boolean modifFecInicioContrato=true;
    if (theUser.getIdPerfil() == Constantes.ID_PERFIL_DIRECTOR || theUser.getIdPerfil() == Constantes.ID_PERFIL_DIRECTOR_TR){
        modifFecInicioContrato = false;
    }     

    boolean isAdminProfile = false;
    if (theUser.getIdPerfil() == Constantes.ID_PERFIL_ADMIN){
        isAdminProfile = true;
    }
%>

<!DOCTYPE html>
<html lang="en">

<head>

    <meta http-equiv=”Content-Type” content=”text/html; charset=UTF-8″>
    <meta name="generator" content="jqueryform.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title> :: Generated By JQueryForm.Com</title>
  	
    <!-- Bootstrap -->
    <link href="<%=request.getContextPath()%>/jqueryform-empleado/css/bootstrap.min.css" rel="stylesheet">
    <link href="<%=request.getContextPath()%>/jqueryform-empleado/css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="<%=request.getContextPath()%>/jqueryform-empleado/css/bootstrap-datepicker3.min.css" rel="stylesheet">
  

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="<%=request.getContextPath()%>/jqueryform-empleado/vendor.css" rel="stylesheet">
    <script type="text/javascript" src="<%=request.getContextPath()%>/js/validarut.js"></script>
    <script>
      
        function setFechaFinContrato(indefinido){
            if (indefinido === 'S'){
                document.getElementById('fechaTerminoContratoAsStr').value='31-12-3000';
            }
        }
      
        function setNuevaFechaIniContrato(continuidad){
            if (continuidad === 'N'){
                document.getElementById("nuevaFechaIniContratoAsStr").readOnly = true;
                document.getElementById('nuevaFechaIniContratoAsStr').value='';
            }else{
                document.getElementById("nuevaFechaIniContratoAsStr").readOnly = false;
            }
        }
      
        function enableDisableFechaDesvinculacion(_estado){
            if (_estado === '1'){
                document.getElementById('fechaDesvinculacionAsStr').disabled = true;
            }else document.getElementById('fechaDesvinculacionAsStr').disabled = false;
        }
      
        function validaForm(){
            if (validateRut('rut')) {
                var estado = document.getElementById('estado').value;
                if (estado === '2'){//no vigente
                    var fecDesvinculacion = document.getElementById('fechaDesvinculacionAsStr').value;
                    if (fecDesvinculacion === ''){
                        alert("Debe ingresar una fecha de desvinculacion");		
                        document.getElementById('fechaDesvinculacionAsStr').focus();
                        $("input[id*=fechaDesvinculacionAsStr]").rules("add", "required");
                        return false;
                    }
                }else{
                    $("input[id*=fechaDesvinculacionAsStr]").rules("remove", "required");
                }
                //alert('rut correcto...');
            }else {
                document.getElementById('rut').focus();
                return false;
            }
        }
                
        function validateRut(fieldNameRut){
            var casillaRut = document.getElementById(fieldNameRut);
            return Rut(casillaRut);
        }		

    </script>
  
    <style type="text/css">
        body{
          background-color: transparent;
        }

        .jf-form{
          margin-top: 28px;
        }

        .jf-form > form{
          margin-bottom: 32px;
        }

        .jf-option-box{
          display: none;
          margin-left: 8px;
        }

        .jf-hide{
          display: none;
        }

        .jf-disabled {
            background-color: #eeeeee;
            opacity: 0.6;
            pointer-events: none;
        }

        /* 
        overwrite bootstrap default margin-left, because the <label> doesn't contain the <input> element.
        */
        .checkbox input[type=checkbox], .checkbox-inline input[type=checkbox], .radio input[type=radio], .radio-inline input[type=radio] {
          position: absolute;
          margin-top: 4px \9;
          margin-left: 0px;
        }

        div.form-group{
          padding: 8px 8px 4px 8px;
        }

        .mainDescription{
          margin-bottom: 10px;
        }

        p.description{
          margin:0px;
        }

        .responsive img{
          width: 100%;
        }

        p.error, p.validation-error{
          padding: 5px;
        }

        p.error{
          margin-top: 10px;
          color:#a94442;
        }

        p.server-error{
          font-weight: bold;
        }

        div.thumbnail{
          position: relative;
          text-align: center;
        }

        div.thumbnail.selected p{
          color: #ffffff;
        }

        div.thumbnail .glyphicon-ok-circle{
          position: absolute;
          top: 16px;
          left: 16px;
          color: #ffffff;
          font-size: 32px;
        }

        .jf-copyright{color: #f5f1f1; display: inline-block; margin: 16px;display:none;}

        .form-group.required .control-label:after {
            color: #dd0000;
            content: "*";
            margin-left: 6px;
        }

        .submit .btn.disabled, .submit .btn[disabled]{
          background: transparent;
          opacity: 0.75;
        }

        /* for image option with span text */
        .checkbox label > span, .radio label > span{
          display: block;
        }

        .form-group.inline .control-label,
        .form-group.col-1 .control-label,
        .form-group.col-2 .control-label,
        .form-group.col-3 .control-label
        {
          display: block;
        }

        .form-group.inline div.radio,
        .form-group.inline div.checkbox{
          display: inline-block;
        }

        .form-group.col-1 div.radio,
        .form-group.col-1 div.checkbox{
          display: block;
        }

        .form-group.col-2 div.radio,
        .form-group.col-2 div.checkbox{
          display: inline-flex;
          width: 48%;
        }

        .form-group.col-3 div.radio,
        .form-group.col-3 div.checkbox{
          display: inline-flex;
          width: 30%;
        }

        .clearfix:after {
           content: ".";
           visibility: hidden;
           display: block;
           height: 0;
           clear: both;
        }
    </style>
</head>

<body>

<!-- ----------------------------------------------- -->
<div class="container jf-form">
<form data-licenseKey="JF-9X6926878C359674T" 
      name="jqueryform-d81043" 
      id="jqueryform-d81043" 
      action='<%=request.getContextPath()%>/EmpleadosController' 
      method='post' 
      enctype='multipart/form-data' 
      novalidate autocomplete="on" 
      onSubmit="return validaForm()" 
      acceptcharset="UTF-8">
<input type="hidden" name="method" value="validateForm">
<input type="hidden" id="serverValidationFields" name="serverValidationFields" value="">

<input type="hidden" name="action" value="<%=strAccion%>">
<input type="hidden" name="action2" value="update">
<input type="hidden" name="auxDepto" id="auxDepto" value="<%=empleado.getDepartamento().getId()%>">
<!-- MAX_FILE_SIZE must precede the file input field -->
<input type="hidden" name="MAX_FILE_SIZE" value="30000" />    
            
<h1><span class="h1">Modificar Empleado</span></h1>

<div class="form-group rut required" data-fid="rut">
  <label class="control-label" for="rut">RUN</label>

<input type="text" 
        class="form-control" 
        id="rut" 
        name="rut" 
        readonly
        value="<%=empleado.getCodInterno()%>"   
        maxlength="12"  
	placeholder="99.999.999-k" 
        data-rule-minlength="9"  
        data-rule-maxlength="12"  
        data-rule-required="true" data-msg-required="Este campo es obligatorio"  
        />
</div>

<div class="form-group cod_interno required" data-fid="cod_interno">
  <label class="control-0label" for="cod_interno">Num Ficha</label>
<input type="text" class="form-control" 
        id="cod_interno" 
        name="cod_interno" 
        readonly 
        value="<%=empleado.getRut()%>" 
        placeholder="99999999-k" 
        data-rule-minlength="7"  
        data-rule-maxlength="13"  
        data-rule-required="true" 
        data-msg-required="Este campo es obligatorio"  
        />
</div>

<div class="form-group nombres required" data-fid="nombres">
  <label class="control-label" for="nombres">Nombres</label>
<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-user"></i> </span>
<input type="text" class="form-control" id="nombres" name="nombres" value="<%=empleado.getNombres()%>" maxlength="70"  placeholder="Ingrese nombres" 
    data-rule-required="true" data-msg-required="Requerido" 
    data-rule-maxlength="70" data-msg-maxlength="No debe exceder de {0} caracteres"   />
</div>
</div>

<div class="form-group apePaterno required" data-fid="apePaterno">
  <label class="control-label" for="apePaterno">Apellido Paterno</label>
<input type="text" class="form-control" id="apePaterno" name="apePaterno" value="<%=empleado.getApePaterno()%>" maxlength="50"  placeholder="Ingrese apellido paterno" 
    data-rule-required="true" data-msg-required="Requerido" 
    data-rule-maxlength="50"   />
</div>

<div class="form-group apeMaterno required" data-fid="apeMaterno">
  <label class="control-label" for="apeMaterno">Apellido Materno</label>


<input type="text" class="form-control" id="apeMaterno" name="apeMaterno" value="<%=empleado.getApeMaterno()%>" maxlength="50"  placeholder="Ingrese apellido materno" 
    data-rule-required="true" data-msg-required="Requerido" 
    data-rule-maxlength="50" data-msg-maxlength="No debe exceder de {0} caracteres"   />
</div>

<div class="form-group fechaNacimientoAsStr required" data-fid="fechaNacimientoAsStr">
  <label class="control-label" for="fechaNacimientoAsStr">Fecha de nacimiento</label>
<div class="input-group date">
<input type="text" class="form-control datepicker" 
		id="fechaNacimientoAsStr" 
		name="fechaNacimientoAsStr" 
        value="<%=empleado.getFechaNacimientoAsStr()%>"  
        placeholder="Ingrese fecha de nacimiento" 
    	data-rule-required="true" 
    	data-msg-required="Requerido"  
    	data-datepicker-format="dd-mm-yyyy"
    	data-datepicker-startView="1" />
</div>
</div>

<div class="form-group direccion required" data-fid="direccion">
  <label class="control-label" for="direccion">Direcci&oacute;n</label>
<input type="text" class="form-control" id="direccion" name="direccion" value="<%=empleado.getDireccion()%>" maxlength="70"  placeholder="Ingrese Direccion. Por ej.: Pasaje Los Boldos 1245, depto 487" 
    data-rule-required="true" data-msg-required="Requerido" 
    data-rule-maxlength="70" data-msg-maxlength="No debe exceder de {0} caracteres"   />
</div>

<div class="form-group email required" data-fid="email">
  <label class="control-label" for="email">Email</label>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-envelope"></i> </span>
<input type="email" class="form-control" id="email" name="email" value="<%=empleado.getEmail()%>"  placeholder="Ingrese correo electronico" 
    data-rule-email="true" 
    data-rule-required="true" data-msg-required="Requerido" 
    data-rule-maxlength="70" data-msg-maxlength="No debe exceder de {0} caracteres"   />
</div>
  
</div>


<div class="form-group radiofoto required" data-fid="radiofoto">
  <label class="control-label" for="radiofoto">Fotograf&iacute;a</label>
        <!-- INICIO Mostrar foto empleado-->
        <%//write image
            try{
                System.out.println("====>Mostrar foto: "+empleado.getPathFoto());
                BufferedImage bImage = ImageIO.read(new File(imagesPath+File.separator+empleado.getPathFoto()));//give the path of an image
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write( bImage, "jpg", baos );
                baos.flush();
                byte[] imageInByteArray = baos.toByteArray();
                baos.close();                                   
                String b64 = DatatypeConverter.printBase64Binary(imageInByteArray);
                %>
                <img  class="img-responsive" src="data:image/jpg;base64, <%=b64%>" width="120" height="120"/>                            
                <% 
            }catch(IOException e){
              System.out.println("Error al mostrar imagen: "+e.getMessage());
            } 
        %>
        Cambiar Foto:
        <select class="form-control" 
                id="cambiarFoto" 
                name="cambiarFoto"   
                data-rule-required="true" 
                data-msg-required="Requerido" >
            <option  value="N" selected>No</option>
            <option  value="S">Si</option>
        </select>
        
  
</div>

<div class="form-group foto required" data-fid="foto">
  <label class="control-label" for="foto">Fotograf&iacute;a</label>

<input type="file" class="form-control" id="foto" name="foto"  value=""   
    data-rule-required="false" data-msg-required=""     data-browseLabel="Seleccione Archivo" data-showUpload="false" data-showZoom="false"/>
  
</div>




<div class="form-group sexo required" data-fid="sexo">
  <label class="control-label" for="sexo">Sexo</label>
    <select class="form-control" id="sexo" name="sexo"   
    data-rule-required="true" data-msg-required="Requerido" >
        <option  value="M">Masculino</option>
        <option  value="F">Femenino</option>
    </select>
</div>


<div class="form-group fono_fijo required" data-fid="fono_fijo">
  <label class="control-label" for="fono_fijo">Tel&eacute;fono Fijo</label>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-earphone"></i> </span>
<input type="tel" class="form-control" id="fono_fijo" name="fono_fijo" value="<%=empleado.getFonoFijo()%>" 
	maxlength="11" 
	placeholder="123 456 789" 
    data-rule-pattern="[0-9 -+.]+" 
    data-msg-pattern="Num de telefono invalido"  
    data-rule-phonenumber="true"
    data-rule-maxlength="11" data-msg-maxlength="Maximo de {0} nÃºmeros"  
    data-rule-minlength="11" data-msg-minlength="Minimo de {0} numeros"
    data-mask="### ### ###"
    data-msg-phonenumber="Verifique numero telefonico" 
    data-rule-required="true" data-msg-required="Requerido"   /></div>

  
</div>

<div class="form-group fono_movil required" data-fid="fono_movil">
  <label class="control-label" for="fono_movil">Tel&eacute;fono m&oacute;vil</label>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-earphone"></i> </span>
<input type="tel" class="form-control" id="fono_movil" 
    name="fono_movil" 
    value="<%=empleado.getFonoMovil()%>"  
    maxlength="11" 
	placeholder="123 456 789" 
    data-rule-pattern="[0-9 -+.]+" 
    data-msg-pattern="Num movil invalido"  
    data-rule-phonenumber="true" 
    data-rule-maxlength="11" data-msg-maxlength="Maximo de {0} nÃºmeros"  
    data-rule-minlength="11" data-msg-minlength="Minimo de {0} numeros"
    data-mask="### ### ###"
     data-msg-phonenumber="Verifique numero movil"  
    data-rule-required="true" data-msg-required="Requerido"   /></div>

  
</div>




<div class="form-group comunaId required" data-fid="comunaId">
  <label class="control-label" for="comunaId">Comuna</label>


<select class="form-control" id="comunaId" name="comunaId"   
    data-rule-required="true" data-msg-required="Requerido" >
  <option value="-1">- Seleccione comuna -</option>
    <%
        Iterator<ComunaVO> iteracomunas = comunas.iterator();
        while(iteracomunas.hasNext() ) {
            ComunaVO auxcomuna = iteracomunas.next();
            %>
            <option value="<%=auxcomuna.getId()%>"><%=auxcomuna.getNombre()%></option>
            <%
        }
    %>
  </select>

  
</div>




<div class="form-group estado required" data-fid="estado">
  <label class="control-label" for="estado">Estado</label>


<select class="form-control" id="estado" name="estado"   
    data-rule-required="true" data-msg-required="Requerido" onChange="enableDisableFechaDesvinculacion(this.value);">
  <option  value="1">Vigente</option>
  <option  value="2">No Vigente</option>
  </select>

  
</div>
<!-- fecha desvinculacion -->
<div class="form-group fechaDesvinculacionAsStr " data-fid="fechaDesvinculacionAsStr">
    <label class="control-label" for="fechaDesvinculacionAsStr">Fecha desvinculacion</label>
    <div class="input-group date">
    <input type="text" class="form-control datepicker" 
           id="fechaDesvinculacionAsStr" 
           name="fechaDesvinculacionAsStr" 
           value="<%=empleado.getFechaDesvinculacionAsStr()%>"  
           placeholder="Ingrese fecha de desvinculacion" 
      data-datepicker-format="dd-mm-yyyy"
      data-datepicker-startView="1" />
    </div>
</div>
<!-- -->
<div class="form-group fechaInicioContratoAsStr required" data-fid="fechaInicioContratoAsStr">
  <label class="control-label" for="fechaInicioContratoAsStr">Fecha inicio contrato</label>

<div class="input-group date">
<input type="text" 
       class="form-control <%if (modifFecInicioContrato){%>datepicker<%}%>" 
		id="fechaInicioContratoAsStr" 
		name="fechaInicioContratoAsStr" 
        value="<%=empleado.getFechaInicioContratoAsStr()%>"  
        placeholder="Ingrese fecha inicio de contrato" 
    	data-rule-required="true" 
        data-msg-required="Requerido"  
  		data-datepicker-format="dd-mm-yyyy"
  		data-datepicker-startView="1" 
                <%if (!modifFecInicioContrato){%>readonly<%}%>/>
  
</div>

<div class="form-group contratoIndefinido required" data-fid="contratoIndefinido">
  <label class="control-label" for="contratoIndefinido">Contrato indefinido</label>
<select class="form-control" id="contratoIndefinido" name="contratoIndefinido"   
    data-rule-required="true" data-msg-required="Requerido" onChange="setFechaFinContrato(this.value);">
  <option  value="S">Si</option>
  <option  value="N">No</option>
  </select>
</div>

<div class="form-group fechaTerminoContratoAsStr " data-fid="fechaTerminoContratoAsStr">
  <label class="control-label" for="fechaTerminoContratoAsStr">Fecha t&eacute;rmino contrato</label>

	<div class="input-group date">
		<input type="text" class="form-control datepicker" id="fechaTerminoContratoAsStr" name="fechaTerminoContratoAsStr" value="<%=empleado.getFechaTerminoContratoAsStr()%>"  placeholder="Ingrese fecha termino de contrato" 
  data-datepicker-format="dd-mm-yyyy"
  data-datepicker-startView="1" />
	</div>

<div class="form-group articulo22 required" data-fid="articulo22">
  <label class="control-label" for="articulo22">Art. 22</label>
<select class="form-control" id="articulo22" name="articulo22"   
    data-rule-required="true" data-msg-required="Requerido" >
  <option  value="S">Si</option>
  <option  value="N">No</option>
  </select>
</div>

<div class="form-group empresaId required" data-fid="empresaId">
  <label class="control-label" for="empresaId">Empresa</label>


<select class="form-control" id="empresaId" name="empresaId"   
    data-rule-required="true" data-msg-required="Requerido" >
  <option selected value="-1">- Seleccione empresa -</option>
 <%
    Iterator<EmpresaVO> iteraempresas = empresas.iterator();
    while(iteraempresas.hasNext() ) {
        EmpresaVO auxempresa = iteraempresas.next();
        %>
        <option value="<%=auxempresa.getId()%>"><%=auxempresa.getNombre()%></option>
        <%
    }
%>
  </select>

  
</div>

<div class="form-group deptoId required" data-fid="deptoId">
  <label class="control-label" for="deptoId">Departamento</label>
<select id="deptoId" name="deptoId"
    data-rule-required="true" data-msg-required="Requerido" >
  <option></option>
  </select>
</div>

<div class="form-group cencoId required" data-fid="cencoId">
  <label class="control-label" for="cencoId">Centro de Costo</label>
<select id="cencoId" name="cencoId"   
    data-rule-required="true" data-msg-required="Requerido" >
  <option></option>
  </select>
</div>

    <div class="form-group idTurno required" data-fid="idTurno">
        <label class="control-label" for="idTurno">Turno</label>
        <select id="idTurno" name="idTurno"   
            data-rule-required="true" data-msg-required="Requerido" >
            <option value="-1">- Seleccione turno -</option>
        </select>
    </div>

<div class="form-group idCargo required" data-fid="idCargo">
  <label class="control-label" for="idCargo">Cargo</label>


<select class="form-control" id="idCargo" name="idCargo"   
    data-rule-required="true" data-msg-required="Requerido" >
  <option value="-1">- Seleccione cargo -</option>
  <%
        Iterator<CargoVO> iteracargos = cargos.iterator();
        while(iteracargos.hasNext() ) {
            CargoVO auxcargo = iteracargos.next();
            %>
            <option value="<%=auxcargo.getId()%>"><%=auxcargo.getNombre()%></option>
            <%
        }
    %>
  </select>

  
</div>

<div class="form-group autorizaAusencia required" data-fid="autorizaAusencia">
  <label class="control-label" for="autorizaAusencia">Autoriza ausencias</label>
<select class="form-control" id="autorizaAusencia" name="autorizaAusencia"   
    data-rule-required="true" data-msg-required="Requerido" >
  <option  value="S">Si</option>
  <option  value="N">No</option>
  </select>
</div>
  
    <div class="form-group claveMarcacion" data-fid="claveMarcacion">
        <label class="control-label" for="claveMarcacion">Clave marcacion</label>
        <input type="text" 
               class="form-control" 
               id="claveMarcacion" 
               name="claveMarcacion" 
               value="<%=empleado.getClaveMarcacion()%>"  
               maxlength="15"  
               placeholder="Ingrese clave marcacion" 
        data-rule-required="false" data-msg-required="Requerido" 
        data-rule-maxlength="15" 
        data-msg-maxlength="No debe exceder de {0} caracteres"   />
    </div>  

    <!-- Oct 2022 -->
    <div class="form-group continuidadLaboral required" data-fid="continuidadLaboral">
      
        <%if (!isAdminProfile){%>   
            <input type="hidden" id="continuidadLaboral" name="continuidadLaboral" value="">
        <%}else{%>
            <label class="control-label" for="continuidadLaboral">Vacaci&oacute;n Progresiva</label>
            <select class="form-control" id="continuidadLaboral" name="continuidadLaboral"   
                data-rule-required="true" 
                data-msg-required="Requerido" 
                onChange="setNuevaFechaIniContrato(this.value);">
                    <option  value="S">Si</option>
                    <option  value="N">No</option>
            </select>
        <%}%>
    </div>
	
        <div class="form-group nuevaFechaIniContratoAsStr " data-fid="nuevaFechaIniContratoAsStr">
            <%if (isAdminProfile){%>   
                <label class="control-label" for="nuevaFechaIniContratoAsStr">Fecha Contrato para Vacaciones Progresivas</label>
            <%}%>
	</div>
	<div class="input-group date">
            <%if (isAdminProfile){%>   
		<input type="text" 
                class="form-control datepicker" 
                id="nuevaFechaIniContratoAsStr" 
                name="nuevaFechaIniContratoAsStr" 
                value="<%=empleado.getNuevaFechaIniContratoAsStr()%>"  
                placeholder="Ingrese nueva fecha de inicio de contrato" 
                        data-datepicker-format="dd-mm-yyyy"
                        data-datepicker-startView="1" />
            <%}else{%>
                <input type="hidden" id="nuevaFechaIniContratoAsStr" name="nuevaFechaIniContratoAsStr" value="">
            <%}%>    
	</div>


  
</div>



    <div class="form-group submit f0 " data-fid="f0" style="position: relative;">
        <label class="control-label sr-only" for="f0" style="display: block;">Submit Button</label>

        <div class="progress" style="display: none; z-index: -1; position: absolute;">
            <div class="progress-bar progress-bar-striped active" role="progressbar" style="width:100%">
            </div>
        </div>

        <button type="submit" class="btn btn-primary btn-lg" style="z-index: 1;">
                      Guardar
        </button>
        <button type="button" class="btn btn-primary btn-lg" style="z-index: 1;" onClick="volver()">
                      Volver
        </button>
    </div>

    <div class="submit" data-redirect="hola.jsp">
        <p class="error bg-warning" style="display:none;"></p>
    </div>

</form>

</div>

<form name="redirectForm" id="redirectForm" method="post" action="<%=request.getContextPath()%>/cruds/empleados.jsp">  
    <input type="hidden" name="cco" id="cco" value="emp01|05|38">  
</form>
    
<div class="container jf-thankyou" 
    style="display:none;" 
    data-redirect="<%=request.getContextPath()%>/mantencion/lista_empleados.jsp" data-seconds="20">
      <h3>Datos actualizados correctamente gracias</h3>
</div>
<!-- ----------------------------------------------- -->


<!-- <script src="<%=request.getContextPath()%>/jqueryform-empleado/js/jquery.min.js"></script> -->
<script src="<%=request.getContextPath()%>/jqueryform-empleado/js/jquery-2.2.4.min.js"></script>

<script src="<%=request.getContextPath()%>/jqueryform-empleado/js/bootstrap.min.js"></script>
<script src="<%=request.getContextPath()%>/jqueryform-empleado/js/bootstrap-datepicker.min.js"></script>
<script src="<%=request.getContextPath()%>/jqueryform-empleado/js/jquery.validate.min.js"></script>
<script src="<%=request.getContextPath()%>/jqueryform-empleado/js/additional-methods.min.js"></script>
<script src="<%=request.getContextPath()%>/jqueryform-empleado/js/jquery.scrollTo.min.js"></script>
<script src="<%=request.getContextPath()%>/jqueryform-empleado/vendor.js" ></script>

<script src="<%=request.getContextPath()%>/jqueryform-empleado/js/jquery.rut.js" type="text/javascript"></script>

<script src="<%=request.getContextPath()%>/jqueryform-empleado/jqueryform.com.min.js?ver=v2.0.3&id=jqueryform-d81043" ></script>

<!-- [ Start: iCheck support ] ---------------------------------- -->
<link href="<%=request.getContextPath()%>/jqueryform-empleado/css/_all.min.css" rel="stylesheet">
<style type="text/css">
/* overwrite bootstrap styles */
.checkbox input[type=checkbox], .checkbox-inline input[type=checkbox], .radio input[type=radio], .radio-inline input[type=radio] {
    position: relative;
    margin-top: 0px;
    margin-left: 2px;
}

.checkbox label, .radio label {
   padding-left: 4px;
}

</style>

<script src="<%=request.getContextPath()%>/jqueryform-empleado/js/icheck.min.js"></script>
<script type="text/javascript">
	;(function ($, undefined)
	{
	
	var checkers = '.icheckbox_flat-blue, .iradio_flat-blue';
	
	function initICheck( $input ){
	  $input.iCheck({
			checkboxClass: 'icheckbox_flat-blue',
			radioClass: 'iradio_flat-blue'
	  }).on('ifClicked', function(e){
		setTimeout( function(){
		  $(e.target).valid();
		  $(e.target).trigger('change').trigger('handleOptionBox');
		}, 250);
	  });
	}; // func
	
	//$('.jf-form .checkbox, .jf-form .radio')
	$('.jf-form input[type="checkbox"], .jf-form input[type="radio"]').each( function( i, e ){
		var $input = $(e), $div = $input.closest('.checkbox,.radio'), hasImg = $div.find('label > img').length;
		if( hasImg ){
                    $input.css({ 'opacity': '0', 'position': 'absolute', 'left': '-1000px', 'right': '-1000px'} );
                }else{
	
                    initICheck( $input );

                    // IE11 and under, the table-cell makes the checkboxes/radio buttons not clickable
                    var isWin = navigator.platform.indexOf('Win') > -1,
                        isEdge = navigator.userAgent.indexOf('Edge/') > -1,
                        noTableCell = isWin && !isEdge;
                    if( !noTableCell ){
                      $div.find('label').css( { display: 'table-cell' } );
                      $(checkers).css( { display: 'table-cell' } );
                    };
	
		};
	});
	
	})(jQuery);

</script>
<!-- [ End: iCheck support ] ---------------------------------- -->


    <!-- [ Start: Select2 support ] ---------------------------------- -->
    <link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/jqueryform-empleado/css/select2.min.css">
    <script type="text/javascript" src="<%=request.getContextPath()%>/jqueryform-empleado/js/select2.full.min.js"></script>
    <style type="text/css">
        .select2-hidden-accessible{
                opacity: 0;
            width:1% !important;
        }
        .select2-container .select2-selection--single{
          height: 34px;
          padding-top: 2px;
          box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
          border: 1px solid #ccc;
        }
        .select2-container--default .select2-selection--single .select2-selection__arrow{
          top: 4px;
        }
    </style>
    <script type="text/javascript">
    ;(function(){

            function templateResult (obj) {
                if (!obj.id) { return obj.text; }

                var img = $(obj.element).data('imgSrc');
                if( img ){
                    return $( '<span><img src="' + img + '" class="img-flag" /> ' + obj.text + '</span>' );
                };

                return obj.text;
            };

            $(".jf-form select").css('width', '90%'); // make it responsive
            $(".jf-form select").select2({
                templateResult: templateResult
            }).change( function(e){
                $(e.target).valid();
            });

    })();
    </script>
    <!-- [ End: Select2 support ] ---------------------------------- -->

    <script type="text/javascript">
    // dropdown fields
    /*;(function(){
      var dataSource = {"f24":{"dependOn":"f23","remote":null,"options":[{"label":"- Seleccione depto -","value":"-1","checked":true},{"label":"Depto 1","checked":false,"value":"1"},{"label":"Depto 2","value":"2","checked":null}]},"f25":{"dependOn":"f24","remote":null,"options":[{"label":"- Seleccione cenco -","value":"-1","checked":true},{"label":"Cenco 1","checked":false,"value":"1"},{"label":"Cenco 2","value":"2","checked":null}]}};
      $(document).trigger( 'dependent:setup', dataSource );
    })();*/
    </script>

    <script type="text/javascript">

        // start jqueryform initialization
        // --------------------------------
        JF.init('#jqueryform-d81043');
	    $(document).ready(function() {
	        $('#empresaId').change(function(event) {
                    var empresaSelected = $("select#empresaId").val();
                    $.get('<%=request.getContextPath()%>/JsonListServlet', {
                        empresaID : empresaSelected
                    }, function(response) {
                        var select = $('#deptoId');
                        select.find('option').remove();
                        var newoption = "";
                        newoption += "<option value='-1'>Seleccione Departamento</option>";
                        for (i=0; i<response.length; i++) {
                            //alert('response[i].id:' + response[i].id+', deptoIdSelected:<%=empleado.getDepartamento().getId()%>');
                            if (response[i].id==='<%=empleado.getDepartamento().getId()%>'){
                                //alert('marcar como selected: <%=empleado.getDepartamento().getId()%>');
                                newoption += "<option value='"+response[i].id+"' id='"+response[i].id+"' selected>"+response[i].nombre+"</option>";
                            }else{
                                newoption += "<option value='"+response[i].id+"' id='"+response[i].id+"'>"+response[i].nombre+"</option>";
                            }
                        }
                        $('#deptoId').html(newoption);
                        setDeptoSelected();
                    });
                });
                                 
                //evento para combo depto
                $('#deptoId').change(function(event) {
                    var empresaSelected = $("select#empresaId").val();
                    var deptoSelected = $("select#deptoId").val();
                    $.get('<%=request.getContextPath()%>/JsonListServlet', {
                        empresaID : empresaSelected,deptoID : deptoSelected
                    }, function(response) {
                        var select = $('#cencoId');
                        select.find('option').remove();
                        var newoption = "";
                        newoption += "<option value='-1'>Seleccione Centro de costo</option>";
                        for (i=0; i<response.length; i++) {
                            newoption += "<option value='"+response[i].id+"' id='"+response[i].id+"'>"+response[i].nombre+"</option>";
                        }
                        $('#cencoId').html(newoption);
                        setCencoSelected();
                    });
                });
                           
                //evento para combo centro costo
                $('#cencoId').change(function(event) {
                    var empresaSelected = $("select#empresaId").val();
                    var deptoSelected = $("select#deptoId").val();
                    var cencoSelected = $("select#cencoId").val();
                    var sourceSelected = 'cargar_turnos_by_cenco';
                    $.get('<%=request.getContextPath()%>/JsonListServlet', {
                       empresaID : empresaSelected,deptoID : deptoSelected,cencoID : cencoSelected,source: sourceSelected
                    }, function(response2) {
                            var select = $('#idTurno');
                            select.find('option').remove();
                            var newoption = "";
                            newoption += "<option value='-1'>Seleccione Turno</option>";
                            for (i2 = 0; i2 <response2.length; i2++) {
                                var idTurno = response2[i2].id;
                                var labelTurno = response2[i2].nombre;
                                newoption += "<option value='" + idTurno + "'>" + labelTurno + "</option>";
                            }
                            $('#idTurno').html(newoption);
                            setTurnoSelected();
                    });
                });
                
                loadValues();
                 
                $.validator.addMethod("rut", function(value, element) {
                    return this.optional(element) || $.Rut.validar(value);
                }, "Este campo debe ser un rut valido.");

                $("#jqueryform-d81043").validate();

                $('#rut').Rut({
                    validation: false
                });
                                
            });     
                          
        function loadValues(){
            //comuna
            $("#comunaId").val(<%=empleado.getComunaId()%>);
            $("#comunaId").change();
            //estado
            $("#estado").val(<%=empleado.getEstado()%>);
            $("#estado").change();
            //Turno
            $("#idTurno").val(<%=empleado.getIdTurno()%>);
            $("#idTurno").change();
            //Turno
            $("#idCargo").val(<%=empleado.getIdCargo()%>);
            $("#idCargo").change();

            //sexo
            $("#sexo").val('<%=empleado.getSexo()%>');
            $("#sexo").change();

            //autoriza ausencia
            <%if (empleado.isAutorizaAusencia()){%>
                    $("#autorizaAusencia").val('S');
            <%}else{%>
                    $("#autorizaAusencia").val('N');
            <%}%>
            $("#autorizaAusencia").change();

            //contrato indefinido
            <%if (empleado.isContratoIndefinido()){%>
                    $("#contratoIndefinido").val('S');
            <%}else{%>
                    $("#contratoIndefinido").val('N');
            <%}%>
            $("#contratoIndefinido").change();

            $("#continuidadLaboral").val('<%=empleado.getContinuidadLaboral()%>');
            $("#continuidadLaboral").change();
            
            //tiene articulo 22
            <%if (empleado.isArticulo22()){%>
                    $("#articulo22").val('S');
            <%}else{%>
                    $("#articulo22").val('N');
            <%}%>
            $("#articulo22").change();

            //empresa
            $("#empresaId").val('<%=empleado.getEmpresa().getId()%>');
            $("#empresaId").change();
                              
            document.getElementById('fechaDesvinculacionAsStr').disabled = true;
            $("input[id*=fechaDesvinculacionAsStr]").rules("remove", "required");
            
            <%if (empleado.getEstado() == 2){%>
                document.getElementById('fechaDesvinculacionAsStr').disabled = false;
            <%}%>
        }
	        
	function setDeptoSelected(){
            var deptoSelected='<%=empleado.getDepartamento().getId()%>';
            var cencoSelected=<%=empleado.getCentroCosto().getId()%>;
            $("#deptoId").val(deptoSelected).trigger("change");
            $("#cencoId").val(cencoSelected);
        }
        
        function setCencoSelected(){
            var cencoSelected=<%=empleado.getCentroCosto().getId()%>;
            $("#cencoId").val(cencoSelected).trigger("change");
            $("#cencoId").val(cencoSelected);
        }
        
        function setTurnoSelected(){
            var turnoSelected=<%=empleado.getIdTurno()%>;
            $("#idTurno").val(turnoSelected).trigger("change");
            $("#idTurno").val(turnoSelected);
        }
        	
        function volver(){
            var auxEmpresaId = $('#empresaId').val();
            var auxDeptoId  = $('#deptoId').val();
            var auxCencoId  = $('#cencoId').val();
            var cencoKey = auxEmpresaId+'|'+auxDeptoId+'|'+auxCencoId;
            
            $('#cco').val(cencoKey);
            document.getElementById("redirectForm").submit();
        }       
                
	</script>

  </body>
</html>